export const INIT_BATCH_TOOL = 'INIT_BATCH_TOOL';
export const HANDLE_INPUT_TOOL = 'HANDLE_INPUT_TOOL';
export const HANDLE_NFTITEM_INPUT_TOOL = 'HANDLE_NFTITEM_INPUT_TOOL';

export const LIST_BULKS_TOKENIDS = 'LIST_BULKS_TOKENIDS';
export const REMOVE_BULKS_TOKENIDS = 'REMOVE_BULKS_TOKENIDS';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_CHAINID = 'GET_CURRENT_CHAINID';

export const GET_APPROVE_BEGIN = 'GET_APPROVE_BEGIN';
export const GET_APPROVE_END = 'GET_APPROVE_END';

export const TRANSFER_BEGIN = 'TRANSFER_BEGIN';
export const TRANSFER_END = 'TRANSFER_END';

export const CHECK_IS_APPROVED = 'CHECK_IS_APPROVED';

export const CONNECT = 'CONNECT';
export const LOG_OUT = 'LOG_OUT';

export const GET_CSV_TOKENIDS = 'GET_CSV_TOKENIDS';
export const REMOVE_CSV_TOKENIDS = 'REMOVE_CSV_TOKENIDS';

export const GET_NFT_ADDRESS_TOKENIDS_BEGIN = 'GET_NFT_ADDRESS_TOKENIDS_BEGIN';
export const GET_NFT_ADDRESS_TOKENIDS_END = 'GET_NFT_ADDRESS_TOKENIDS_END';

export const GET_NFT_LIST_BEGIN = 'GET_NFT_LIST_BEGIN';
export const GET_NFT_LIST_ING = 'GET_NFT_LIST_ING';
export const GET_NFT_LIST_END = 'GET_NFT_LIST_END';
export const SHOW_NFT_LIST = 'SHOW_NFT_LIST';

export const DECONSTRUCT_CSV = 'DECONSTRUCT_CSV';

export const DENY_TRANSFER = 'DENY_TRANSFER';

export const CHECK_ISUNLOCKED = 'CHECK_ISUNLOCKED';

export const CHECK_ADDR_IS_CONTRACT = 'CHECK_ADDR_IS_CONTRACT';
export const ERC_721_CHECK = 'ERC_721_CHECK';
export const ERC_1155_CHECK = 'ERC_1155_CHECK';

export const ADDR_IS_NOT_CONTRACT = 'ADDR_IS_NOT_CONTRACT';

export const NFTADDRESS_IS_EMPTY = 'NFTADDRESS_IS_EMPTY';

export const IMPORT_RECIPIENT = 'IMPORT_RECIPIENT';
export const CLEAN_ALL_NFT_RECIPIENT = 'CLEAN_ALL_NFT_RECIPIENT';
