export const INIT_BATCH_TOOL = 'INIT_BATCH_TOOL';
export const HANDLE_INPUT_TOOL = 'HANDLE_INPUT_TOOL';

export const GET_OWNER = 'GET_OWNER';

export const GET_APPROVE_BEGIN = 'GET_APPROVE_BEGIN';
export const GET_APPROVE_END = 'GET_APPROVE_END';

export const TRANSFER_BEGIN = 'TRANSFER_BEGIN';
export const TRANSFER_END = 'TRANSFER_END';

export const CHECK_IS_APPROVED = 'CHECK_IS_APPROVED';
export const INIT_IS_APPROVED = 'INIT_IS_APPROVED';
